import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<body
  className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>
  <header
    style={{
      display: "flex",
      gap: 12,
      padding: 12,
      borderBottom: "1px solid #ddd",
    }}
  >
    <strong>STR Finance</strong>

    <nav style={{ marginLeft: "auto", display: "flex", gap: 12 }}>
      <Link href="/">Main</Link>
      <Link href="/owner">Owner</Link>
    </nav>
  </header>

  <main style={{ padding: 12 }}>
    {children}
  </main>
</body>
    </html>
  );
}
